# Generated by Django 4.2.4 on 2023-09-07 14:45

from django.db import migrations
from django.utils.text import slugify

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_category'),
    ]

    def create_categories(apps, schema_editor):
        Category = apps.get_model('shop', 'Category')
        categories_arr = ["Women", "Men", "Accesories"]
        for category in categories_arr:
            cat = Category(title=category,slug=slugify(category))
            cat.save()

    operations = [
        migrations.RunPython(create_categories),
    ]

